version: '3.5'

services:
  ### Jesse's Workspace ################################################
  jesse:
    image: salehmir/jesse:latest
    tty: true
    env_file:
      - ../.env
    ports:
      - "9000:9000"
      # Jupyter Port
      - "8888:8888"
    volumes:
      - ../:/home
    container_name: jesse
    command: bash -c "jesse install-live --no-strict && jesse run"